version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_TYPE: ${DB_TYPE}
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - blog-network
    command: >
      sh -c "migrate -path=/migrations -database=${POSTGRESQL_URL} up && ./blog-api"

networks:
  blog-network:

volumes:
  pgdata:
